### ISSUE TITLE
是不是都不想写第二章的例子

### ISSUE THREAD

**Issue by momognu** [MaximusZhou/APUE#1]
全是些打印界限值的代码，本来也是嫌麻烦找个贴出来看看来着，谁知道个个都不写Σ( ° △ °|||)︴

**Comment by MaximusZhou** [comment]
第二章的代码对学习帮助不是很大，所以就没写了。

**Comment by momognu** [comment]
@MaximusZhou 是呀，觉得应用过程中查一下就行了
